import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = join(import.meta.dirname, '..');
const skillPath = join(root, '.claude', 'skills', 'youtube-relay', 'SKILL.md');
const outDir = join(root, 'src', 'generated');
const outPath = join(outDir, 'skill.ts');

const contents = readFileSync(skillPath, 'utf8');

mkdirSync(outDir, { recursive: true });

writeFileSync(
  outPath,
  `// Auto-generated by scripts/generate-skill.ts — do not edit manually.\nexport const youtubeRelaySkill = ${JSON.stringify(contents)};\n`,
);

console.log(`generate-skill: wrote ${outPath}`);
