import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { stripFrontmatter } from '../src/frontmatter.ts';

const root = join(import.meta.dirname, '..');
const skillPath = join(root, '.claude', 'skills', 'youtube-relay', 'SKILL.md');
const outDir = join(root, 'src', 'generated');
const outPath = join(outDir, 'skill.ts');

// The frontmatter exists so Claude Code can discover the skill; embedders want
// the prose only.
const contents = stripFrontmatter(readFileSync(skillPath, 'utf8'));

mkdirSync(outDir, { recursive: true });

writeFileSync(
  outPath,
  `// Auto-generated by scripts/generate-skill.ts — do not edit manually.\nexport const youtubeRelaySkill = ${JSON.stringify(contents)};\n`,
);

console.log(`generate-skill: wrote ${outPath}`);
